### ISSUE TITLE
Question about the version in package.json

### ISSUE THREAD

**Issue by gillpeacegood** [zamotany/module-federation-repack#2]
Your package.json files don't use a standard release of re.pack, I am just wondering whether whatever code changes are on that release would be needed for me to experiment with module federation?

**Comment by zamotany** [comment]
It doesn't but all the necessary changes in Re.Pack were already integrated into main version, so you can freely use `2.5.1` version of Re.Pack. Just keep in mind that there were some changes to `ChunkManager`'s `resolveRemoteChunk`: https://re-pack.netlify.app/docs/api/react-native/interfaces/RemoteChunkLocation so you will need to adjust the code.
