### ISSUE TITLE
ChunkManager.loadChunk invocation failed

### ISSUE THREAD

**Issue by LauColombini** [zamotany/module-federation-repack#5]
I follow the steps, everything is fine, but at that point I already want to open the host app on my device. throws this error in the shell

`ChunkManager.loadChunk invocation failed: Failed to connect to localhost/127.0.0.1:9000 [NetworkFailure] {"absolute": false, "body": undefined, "fetch": true, "headers": undefined, "method": "GET", "query": "platform=android", "timeout": 30000, "url": "http://localhost:9000/app1.container.bundle"} `

Thank you very much for the repository, it is being very helpful, we want to implement it in Chiper App...

**Comment by TMaszko** [comment]
Hi, Please try this command `adb reverse tcp:9000 tcp:9000` and restart the app :)

**Comment by LauColombini** [comment]
Perfect !!

**Comment by LauColombini** [comment]
love you guys
